[pytest]
testpaths = tests
addopts = -p no:logfire --cov=dags/spotify/include --cov=dags/research/include --cov-report=term-missing --cov-fail-under=80
filterwarnings =
    ignore:ImportError while loading the `logfire-plugin` Pydantic plugin.*:UserWarning
